export function bandera(country) {
  const banderas = {
    France: "banderaFrancia",
    Switzerland: "banderaSwitzerland",
    Morocco: "banderaMarruecos",
    Austria: "banderaAustria",
    Brazil: "banderaBrasil",
    Italy: "banderaItalia",
    Bulgaria: "banderaBulgaria",
    macedonia: "banderaMacedonia",
    Japan: "banderaJapon",
    Mexico: "banderaMexico",
    Ethiopia: "banderaEthiopia",
    Serbia: "banderaSerbia",
    Romania: "banderaRomania",
    Spain: "banderaEspania",
    Slovenia: "banderaEslovenia",
    Usa: "banderaUsa",
    Turkey: "banderaTurkia",
    "South korea": "banderaKorea",
    Tunisia: "banderaTunisia",
    "Czech republic": "banderaCheca",
    "Bosnia and herzegovina": "banderaBosnia",
    Germany: "banderaAlemania",
    Portugal: "banderaPortugal",
    Thailand: "banderaTailandia",
    Indonesia: "banderaIndonesia",
    "United kingdom": "banderaReinoUnido",
    World: "banderaWorld",
    Netherlands: "bandareraNetherlands",
    Belgium: "banderaBelgica",
    China: "banderaChina",
    Denmark: "banderaDinamarca",
    Taiwan: "banderaTaiwan",
    "Puerto rico": "banderaPuertoRico",
    Colombia: "banderaColombia",
    Israel: "banderaIsrael",
    Poland: "banderaPolonia",
    Slovakia: "banderaSlovakia",
    Sweden: "banderaSweden",
  };

  return banderas[country] || ""; // Devuelve el estilo de la bandera o una cadena vacía si no se encuentra el país
}
