export function mapPlayerImage(playerName) {
	const playerImageMap = {
		"Djokovic N.": "/img/players_men/djokovic.png",
		"Added": "/img/players_men/dan-added.png",
		"Marterer": "/img/players_men/maximilian-marterer.png",
		"Coppejans": "/img/players_men/kimmer-coppejans.png",
		"Hong S. C.": "/img/players_men/seong_chan-hong.png",
		"Ionel N. D.": "/img/players_men/nicholas-david-lonel.png",
		"Stricker": "/img/players_men/dominic-stricker.png",
		"Sels J": "/img/players_men/sels_jelle.png",
		"Svrcina": "/img/players_men/svrcina-dalibor.png",
		"Riedi L": "/img/players_men/leandro-riedi.png",
		"Tirante": "/img/players_men/thiago-tirante.png",
		"Hijikata": "/img/players_men/rinky-hijikata.png",
		"Bagnis": "/img/players_men/facundo-bagnis.png",
		"Couacaud": "/img/players_men/enzo-couacaud.png",
		"Misolic": "/img/players_men/filip-misolic.png",
		"De Loore": "/img/players_men/joris-de-loore.png",
		"Collarini": "/img/players_men/andrea-collarini.png",
		"Furness": "/img/players_men/evan-furness.png",
		"Holt B.": "/img/players_men/brandon-holt.png",
		"Rodionov J.": "/img/players_men/jurij-rodionov.png",
		"Shang J.": "/img/players_men/juncheng-shang.png",
		"Cuevas P.": "/img/players_men/pablo-cuevas.png",
		"Tu L.": "/img/players_men/li-tu.png",
		"Marozsan F": "/img/players_men/marozsan.png",
		"Cerundolo J. M." : "/img/players_men/juan-manuel-cerundolo.png",
		"Svajda Z.": "/img/players_men/zachary-svajda.png",
		"Giustino L.": "/img/players_men/lorenzo-giustino.png",
		"Ferreira Silva F.": "/img/players_men/ferreira_silva.png",
		"Bergs Z.": "/img/players_men/zizou-bergs.png",
		"Mochizuki S.": "/img/players_men/shintaro-mochizuki.png",
		"Peniston R.": "/img/players_men/ryan-peniston.png",
		"Celikbilek A.": "/img/players_men/altuq-celikbilek.png",
		"Vavassori A.": "/img/players_men/andrea-vavassori.png",
		"Zeppieri G.": "/img/players_men/zeppieri_giulio.png",
		"Basilashvili N.": "/img/players_men/nikoloz-basilashvili.png",
		"Albot R.": "/img/players_men/radu-albot.png",
		"Kopriva V.": "/img/players_men/vit-kopriva.png",
		"Gakhov I.": "/img/players_men/ivan-gakhov.png",
		"Medjedovic H.": "/img/players_men/hamad-medjedovic.png",
		"Gojo B.": "/img/players_men/borna-gojo.png",
		"Dzumhur D.": "/img/players_men/damir-dzumhur.png",
		"Gueymard Wayenburg S.": "/img/players_men/gueymard-wayenburg.png",
		"Kudla D.": "/img/players_men/denis-kudla.png",
		"Nardi L.": "/img/players_men/luca-nardi.png",
		"Tabilo A.": "/img/players_men/alejandro-tabilo.png",
		"Neuchrist M.": "/img/players_men/maximilian-neuchrist.png",
		"De Jong J.": "/img/players_men/jesper-de-jong.png",
		"Sousa J.": "/img/players_men/joau-sousa.png",
		"Rodriguez Taverna S.": "/img/players_men/rodriguez-taverna.png",
		"Tseng C. H.": "/img/players_men/chun-hsin-tseng.png",
		"Ritschard A.": "/img/players_men/alexander-ritschard.png",
		"Ugo Carabelli C.": "/img/players_men/camilo-carabelli.png",
		"Uchida K.": "/img/players_men/uchida_kaichi.png",
		"Gombos N.": "/img/players_men/norbert-gombos.png",
		"Machac T.": "/img/players_men/tomas-machac.png",
		"Pouille L.": "/img/players_men/lucas-pouille.png",
		"Agamenone F.": "/img/players_men/franco-agamenone.png",
		"Diaz Acosta F.": "/img/players_men/diaz-acosta.png",
		"Kolar Z.": "/img/players_men/zdenek-kolar.png",
		"Barrios Vera T.": "/img/players_men/marcelo-tomas-barrios.png",
		"Kovalik J.": "/img/players_men/jozef-kovalik.png",
		"Berankis R.": "/img/players_men/ricardas-berankis.png",
		"Brancaccio R.": "/img/players_men/raul-brancaccio.jpg",
		"Blancaneaux G.": "/img/players_men/geoffrey-blancaneaux.png",
		"Ilkel C.": "/img/players_men/ilkel_cem.png",
		"Bolt A.": "/img/players_men/alex-bolt.png",
		"Krutykh O.": "/img/players_men/oleksii-krutykh.png",
		"Choinski J.": "/img/players_men/jan-choinski.png",
		"Kicker N.": "/img/players_men/nicolas-kicker.png",
		"Delbonis F.": "/img/players_men/federico-delbonis.png",
		"Mejia N.": "/img/players_men/nicolas-mejia.png",
		"Duckworth J.": "/img/players_men/james-duckworth.png",
		"Bonadio R.": "/img/players_men/riccardo-bonadio.png",
		"Cobolli F.": "/img/players_men/flavio-cobolli.png",
		"Ficovich J. P.": "/img/players_men/ficovich-juan-pablo.png",
		"Brouwer G.": "/img/players_men/gijs-brouwer.png",
		"Broady L.": "/img/players_men/liam-broady.png",
		"Gerasimov E.": "/img/players_men/gerasimov-egor.png",
		"Lokoli L.": "/img/players_men/laurent-lokoli.png",
		"Hanfmann Y.": "/img/players_men/yannick-hanfmann.png",
		"Bellucci M.": "/img/players_men/mattia-bellucci.png",
		"Hardt N.": "/img/players_men/nick-hardt.png",
		"Hsu Yu H.": "/img/players_men/yu-hsiou-hsiou.png",
		"Karatsev A.": "/img/players_men/aslan-karatsev.png",
		"Herbert P.": "/img/players_men/pierre-huques-herbert.png",
		"Kotov P.": "/img/players_men/pavel-kotov.png",
		"Geerts M.": "/img/players_men/michael-geerts.png",
		"Laaksonen H.": "/img/players_men/henri-laaksonen.png",
		"Olivieri G. A.": "/img/players_men/genaro-alberto-olivieri.png",
		"Maestrelli F.": "/img/players_men/francesco-maestrelli.png",
		"Andreev A.": "/img/players_men/adrian-andreev.png",
		"Nava E.": "/img/players_men/emilio-nava.png",
		"Kuzmanov D.": "/img/players_men/dimitar-kuzmanov.png",
		"Klein L.": "/img/players_men/lukas-klein.png",
		"Ofner S.": "/img/players_men/sebastian-ofner.png",
		"Noguchi R.": "/img/players_men/rio-noguchi.png",
		"Piros Z.": "/img/players_men/zsombor-piros.png",
		"Koepfer D.": "/img/players_men/dominik-koepfer.png",
		"Polmans M.": "/img/players_men/marc-polmans.png",
		"Polmans M.": "/img/players_men/marc-polmans.png",
		"Mayot H.": "/img/players_men/harold-mayot.png",
		"Seyboth Wild T.": "/img/players_men/thiago-seyboth-wild.png",
		"Bellier A.": "/img/players_men/antoine-bellier.png",
		"Skatov T.": "/img/players_men/timofev-skatov.png",
		"Virtanen O.": "/img/players_men/otto-virtanen.png",
		"Escoffier A.": "/img/players_men/antoine-escoffier.png",
		"Watanuki Y.": "/img/players_men/yosuke-watanuki.png",
		"Pellegrino A.": "/img/players_men/andrea-pellegrino.png",
		"Wu Tung-Lin": "/img/players_men/wu-tung-lin.png",
		"Meligeni Alves F.": "/img/players_men/meligeni_felipe.png",
		"Jarry N.": "/img/players_men/nicolas-jarry.png",
		"Lajovic D.": "/img/players_men/dusan-lajovic.png",
		"Mannarino A.": "/img/players_men/adrian-mannarino.png",
		"Krajinovic F.": "/img/players_men/filip-krajinovic.png",
		"Zapata Miralles B.": "/img/players_men/bernabe-zapata_miralles.png",
		"Sachko V.": "/img/players_men/vitaliy-sachko.png",
		"Rincon D.": "/img/players_men/daniel-rincon.png",
		"Carballes Baena R.": "/img/players_men/roberto-carballes-baena.png",
		"Wu Y.": "/img/players_men/yibing-wu.png",
		"Huesler M.": "/img/players_men/marc-andrea-huesler.png",
		"Bublik A.": "/img/players_men/alexander-bublik.png",
		"Giron M.": "/img/players_men/marcos-giron.png",
		"Dellien H.": "/img/players_men/hugo-dellien.png",
		"Wolf J.J.": "/img/players_men/jj-wolf.png",
		"Pella G.": "/img/players_men/guido-pella.png",
		"Ivashka I.": "/img/players_men/ilya-ivashka.png",
		"Serdarusic N.": "/img/players_men/serdarusic_nino.png",
		"O'Connell C.": "/img/players_men/oconnell_christopher.png",
		"Travaglia S.": "/img/players_men/stefano-travaglia.png",
		"Griekspoor T.": "/img/players_men/tallon-griekspoor.png",
		"Zverev A.": "/img/players_men/alexander-zverev.png",
		"Eubanks C.": "/img/players_men/christopher-eubanks.png",
		"Goffin D.": "/img/players_men/david-goffin.png",
		"Hurkacz H.": "/img/players_men/hubert-hurkacz.png",
		"Khachanov K.": "/img/players_men/karen-khachanov.png",
		"Lestienne C.": "/img/players_men/constant-lestienne.png",
		"Kypson P.": "/img/players_men/patrick-kypson.png",
		"Cressy M.": "/img/players_men/maxime-cressy.png",
		"Arnaldi M.": "/img/players_men/matteo-arnaldi.png",
		"Galan D. E.": "/img/players_men/daniel-galan.png",
		"Fucsovics M.": "/img/players_men/marton-fucsovics.png",
		"Grenier H.": "/img/players_men/hugo-grenier.png",
		"Isner J.": "/img/players_men/john-isner.png",
		"Borges N.": "/img/players_men/nuno-borges.png",
		"Kokkinakis T.": "/img/players_men/thanasi-kokkinakis.png",
		"Evans D.": "/img/players_men/daniel-evans.png",
		"Kubler J.": "/img/players_men/kubler-jason.png",
		"McDonald M.": "/img/players_men/mackenzie-mcdonald.png",
		"Vesely J.": "/img/players_men/jiry-vesely.png",
		"Tsitsipas S.": "/img/players_men/stefanos-tsitsipas.png",
		"Cazaux A.": "/img/players_men/arthur-cazaux.png",
		"Moutet C.": "/img/players_men/corentin-moutet.png",
		"Djere L.": "/img/players_men/laslo-djere.png",
		"Rublev A.": "/img/players_men/andreay-rublev.png",
		"Alcaraz C.": "/img/players_men/carlos-alcaraz.png",
		"Shelton B.": "/img/players_men/ben-shelton.png",
		"Sonego L.": "/img/players_men/lorenzo-sonego.png",
		"Musetti L.": "/img/players_men/lorenzo-musetti.png",
		"Ymer M.": "/img/players_men/mikael-ymer.png",
		"Kovacevic A.": "/img/players_men/kovacevic-aleksandar.png",
		"Rune H.": "/img/players_men/holder-rune.png",
		"Medvedev D.": "/img/players_men/dani-medvedev.png",
		"Shevchenko A.": "/img/players_men/alexander-shevchenko.png",
		"Otte O.": "/img/players_men/oscar-otte.png",
		"Sinner J.": "/img/players_men/sinner.png",
		"Altmaier D.": "/img/players_men/daniel-altmaier.png",
		"Mpetshi Perricard G.": "/img/players_men/perricard-mpetshi.png",
		"Nishioka Y.": "/img/players_men/yoshihito-nishioka.png",
		"Paul T.": "/img/players_men/tomy-paul.png",
		"Purcell M.": "/img/players_men/max-purcell.png",
		"Thompson J.": "/img/players_men/jordan-thompson.png",
		"Kecmanovic M.": "/img/players_men/miomir-kecmanovic.png",
		"Ymer E.": "/img/players_men/elias-ymer.png",
		"Ruud C.": "/img/players_men/casper-ruud.png",
		"Gaston H.": "/img/players_men/hugo-gaston.png",
		"Molcan A.": "/img/players_men/alex-molcan.png",
		"Harris L.": "/img/players_men/lloyd-harris.png",
		"Cerundolo F.": "/img/players_men/francisco-cerundolo.png",
		"Munar J.": "/img/players_men/jaume-munar.png",
		"Halys Q.": "/img/players_men/quentin-halys.png",
		"Monteiro T.": "/img/players_men/thiago-monteiro.png",
		"Ruusuvuori E.": "/img/players_men/emil-ruusuvuori.png",
		"Barrere G.": "/img/players_men/gregorie-barrere.png",
		"Gasquet R.": "/img/players_men/richard-gasquet.png",
		"Rinderknech A.": "/img/players_men/arthur-rinderknech.png",
		"Mmoh M.": "/img/players_men/michael-mmoh.png",
		"Fritz T.": "/img/players_men/taylor-fritz.png",
		"Dimitrov G.":"/img/players_men/grigor-dimitrov.png",
		"Monfils G.":"/img/players_men/gael-monfils.png",
		"Baez S.":"/img/players_men/sebastian-baez.png",
		"Daniel T.":"/img/players_men/taro-daniel.png",
		"Shapovalov D.":"/img/players_men/denis-shapovalov.png",
		"Bautista-Agut R.":"/img/players_men/bautista-agut.png",
		"Varillas J. P.":"/img/players_men/juanpablo-varillas.png",
		"Coric B.":"/img/players_men/borna-coric.png",
		"Cachin P.":"/img/players_men/pedro-cachin.png",
		"Etcheverry T. M.":"/img/players_men/tomas-etcheverry.png",
		"De Minaur A.":"/img/players_men/alex-de-minaur.png",
		"Fognini F.":"/img/players_men/fabio-fognini.png",
		"Tiafoe F.":"/img/players_men/frances-tiafoe.png",
		"Lehecka J.":"/img/players_men/jjiri-lehecka.png",
		"Korda S.":"/img/players_men/sebastian-korda.png",
		"Norrie C.":"/img/players_men/cameron-norrie.png",
		"Schwartzman D.":"/img/players_men/diego-schwartzman.png",
		"Humbert U.":"/img/players_men/ugo-humbert.png",
		"van Assche L.":"/img/players_men/luca-van-assche.png",
		"Davidovich Fokina A.":"/img/players_men/davidovich-fokina.png",
		"Wawrinka S.":"/img/players_men/stan-wawrinka.png",
		"Ram R.":"/img/players_men/rajeev-ram.png",
		"Salisbury J.":"/img/players_men/joe-salisbury.png",
		"Koolhof W.":"/img/players_men/wesley-koolhof.png",
		"Skupski N.":"/img/players_men/neal-skupski.png",
	}

	if (playerName in playerImageMap) {
		return playerImageMap[playerName];
	}
	return "/img/default-player.png";
}

